basic:
    name: dallasftworth.teach.org
    environments:
        production: 'https://dallasftworth.teach.org'
        staging: 'https://dallasftworth.staging-5em2ouy-tsy4np5h7paxs.us-2.platformsh.site'
        development: 'https://dallasftworth.develop-sr3snxi-tsy4np5h7paxs.us-2.platformsh.site'
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: '', password: '' }
        development: { user: '', password: '' }
    breakpoints:
        - 320
        - 640
        - 1024
        - 1200
    pages:
        - /
        - /guides/prepare-certification-tests-dallas-fort-worth
        - /programs/deadlines
        - '/programs?teachTPP=eyJvciI6WzYwM119'
        - /services/application-checklists
        - '/aid?teachAid=eyJyIjpbNjAzXSwiYXQiOlsiOTMiLCI5NSIsIjk2Il19'
        - /try-out-teaching
        - /schools-community
        - '/programs/texas-am-university-commerce?programId=9d0fcafe-905d-4656-864c-264bac9af700'
        - /checklists/27131
        - /articles
        - /articles/their-beautiful-image
        - /events
    monitoring:
        days: {  }
        type: ''
        schedule_time: '01:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: "#lhnHocButton>div.lhnHocChatBtnCont\ndiv.e1b25jbg0\ndiv#lhnHelpOutCenter\ndiv[role='alertdialog']"
    delay: 5
    scroll: false
    headers:
        - { value: '', header: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { type: title, selector: '' }
    sensitivity: 0
    night_mode: false
    retina_images: false
    single_ip: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: '2'
        workers_nonproduction: '1'
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: false
